version: 2.1

executors:
  builder:
    machine: true
  deployer:
    docker:
      - image: minepicco/cc-build-image:latest

workflows:
  version: 2.1
  
  build-deploy:
    jobs:
      - build_scan:
          context: webpage_deployment

jobs:
  build_scan:
    executor: deployer
    
    environment:
      imagename: "minepicco"
      
    steps:
      - checkout
                     
      - run:
          name: Build Image
          command: |
            sudo docker login -u $docker_user -p $docker_pass
            sudo docker build --tag $imagename"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM .

      - run:
          name: simple test
          command: |
            sudo docker run --rm --name web -p 80:80 -d $imagename"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM
            sleep 1 && curl http://localhost
            sudo docker stop web

      - run:
          name: Twistlock Vuln/Compliance check
          command: |
            curl -k -u $tl_u:$tl_p --output twistcli $TL_URL"/api/v1/util/twistcli"
            chmod +x twistcli
            ./twistcli images scan --details --address $TL_URL -u $tl_u -p $tl_p --ci $imagename"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM 

